[tox]
envlist = py310,py311,py312,py313,lint,dist-check,security
skip_missing_interpreters = True
isolated_build = True

[testenv]
deps = -r {toxinidir}/test-requirements.txt

commands = pytest -v tests/
recreate = true

[testenv:lint]
deps =
    ruff
commands =
    ruff format --check src/ tests/
    ruff check src/ tests/

[testenv:dist-check]
deps =
    twine
    build
commands =
    python -m build --outdir {toxworkdir}/dist
    twine check {toxworkdir}/dist/*

[testenv:security]
deps =
    bandit

; ignoring errors
commands =
    - bandit -r src/err_backend_discord/
